default: &default
  openai_api_key: <%= ENV['OPENAI_API_KEY'] %>
  aws:
    access_key_id: <%= ENV['ACCESS_KEY_ID'] %>
    secret_access_key: <%= ENV['SECRET_ACCESS_KEY'] %>


development:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
